### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by MarMarIV**
Attribute maxSdk removed

Update by forked repo: https://github.com/strazzere/anti-emulator/issues/19

### CODE REVIEW

**Comment by jerry2007** [comment]
Wineed this also...
Please merge this PR @nmilcoff

**Review by nmilcoff — APPROVED** [review]
Thank you!

**Comment by MarMarIV** [comment]
@nmilcoff Can you please approve release for NuGet publish? (https://dev.azure.com/nicolasmilcoff/AntiEmulator/_releaseProgress?_a=release-pipeline-progress&releaseId=3)

I want to create next PRQ on BreachDetector

Thanks

**Comment by nmilcoff** [comment]
Done! Thank you for taking care of that too ❤️

**Pull request merged**
