### PR TITLE
AAR library replaced

### PR DESCRIPTION
**Pull request by MarMarIV**
AAR library with AndroidMaxSdk removed

### CODE REVIEW

**Comment by jerry2007** [comment]
@nmilcoff  please 👍

**Comment by nmilcoff** [comment]
Hey guys, thanks for this PR! @MarMarIV can you please elaborate on the removal of the AAR? I think it should be replaced , not removed 🤔

**Comment by MarMarIV** [comment]
@nmilcoff AAR library is replaced in this PR, not removed (just only few bytes smaller)

**Comment by nmilcoff** [comment]
Ok, cool! Can you please confirm removing the AndroidMaxSdk is the only change made to the AAR?

**Comment by MarMarIV** [comment]
@nmilcoff I make push with new AAR packege, with only MaxSdk removed

**Review by nmilcoff — APPROVED** [review]
Thank you!

**Pull request merged**
